import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from 'vitest';
import { bundle } from '../src/bundler/bundler.js';

test('checked-in async CLI artifact is generated by the bundler', async () => {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
  const generated = await bundle({ rootDir: path.join(root, 'fixtures/cli-async'), project: 'fixture', target: 'test' });
  expect(generated.diagnostics).toEqual([]);
  const artifactPath = path.join(root, 'fixtures/cli-async/artifact.json');
  const normalize = (value: any) => {
    const result = JSON.parse(JSON.stringify(value));
    for (const mod of result.modules ?? []) for (const imp of mod.imports ?? []) {
      if (imp.position?.file) imp.position.file = path.relative(root, imp.position.file).replaceAll('\\', '/');
    }
    return result;
  };
  const normalized = normalize(generated.artifact);
  if (process.env.UPDATE_PBVEX_CLI_ARTIFACT === '1') {
    await writeFile(artifactPath, JSON.stringify(normalized, null, 2) + '\n');
  }
  const checkedIn = JSON.parse(await readFile(artifactPath, 'utf8'));
  expect(normalized).toEqual(checkedIn);
});
