package storage

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/tools/filesystem"
	"github.com/pocketbase/pocketbase/tools/hook"
)

// Native PocketBase record file writes are covered by core.App hooks. The
// pinned upstream (PocketBase v0.40.1) performs the actual filesystem
// writes of record uploads inside the system FileField interceptor bound at
// priority 99 on OnRecordCreateExecute/OnRecordUpdateExecute, and performs
// post-commit file deletions inside interceptors bound at priority -99 on
// the After*Success/After*Error hooks. Handlers registered here use
// priorities that run before actual writes (reservation) and after
// upstream commit/cleanup steps (settlement, credit, release):
//
//   - Create/UpdateExecute (priority 0, upstream writes at 99):
//     reserve worst-case bytes before any upload write.
//   - AfterCreate/AfterUpdateSuccess (priority 0, upstream at -99):
//     settle reservations to actual bytes and credit confirmed deletions.
//   - AfterCreate/AfterUpdateError (priority 0, upstream cleanup at -99):
//     release only when every uploaded object is verified absent;
//     otherwise keep the reservation for provider reconciliation.
//   - AfterDeleteSuccess (priority -100 pre-pass for sizes, priority 0
//     credit pass): credit the captured file bytes at the deletion commit;
//     the upstream prefix deletion itself is asynchronous.
//
// On-demand native thumbnails are generated by the files download route
// (apis/file.go) after route matching but before serving, with no core
// hook in between; a global request middleware below reserves before that
// write using an exact replica of the upstream generation conditions.
//
// The install is idempotent: handlers carry fixed hook ids and are safe to
// rebind. It must be called with an attached quota observer; standalone
// services (nil observer) are unchanged and install nothing.

const (
	nativeQuotaUploadStashKey      = "@pbvexQuotaUploads"
	nativeQuotaDeleteStashKey      = "@pbvexQuotaDeletes"
	nativeQuotaReservationStashKey = "@pbvexQuotaReservation"

	// nativeDefaultThumbSizes mirrors the unexported apis.defaultThumbSizes
	// of the pinned upstream: the only selector natively generated for file
	// fields that do not declare thumbs. Keep in sync when bumping
	// PocketBase.
	nativeDefaultThumbSizes = "100x100"
)

// nativeUpload records one uploaded or removed native file with its exact
// on-disk size at the time it was observed, plus the byte total of its
// thumb variants when they were captured before a removal.
type nativeUpload struct {
	Field      string
	Name       string
	Size       int64
	ThumbBytes int64
}

// InstallNativeQuotaHooks installs the native record file quota hooks and
// the native thumbnail request gate on the app. It returns nil without
// installing anything when no quota observer is attached (standalone
// mode), so wiring it unconditionally preserves existing semantics.
func (s *Service) InstallNativeQuotaHooks(app core.App) error {
	if app == nil {
		return errors.New("storage: InstallNativeQuotaHooks requires a core.App")
	}
	if !s.hasQuota() {
		return nil
	}
	if s.nativeVariants == nil {
		s.nativeVariants = newNativeVariantGate()
	}

	// Reservation before actual uploads. Upstream writes at priority 99.
	app.OnRecordCreateExecute().Bind(&hook.Handler[*core.RecordEvent]{
		Id:       "pbvexStorageQuotaCreateExecute",
		Priority: 0,
		Func: func(e *core.RecordEvent) error {
			if err := s.nativeReserveUpload(e.Context, e.Record); err != nil {
				return err
			}
			return e.Next()
		},
	})
	app.OnRecordUpdateExecute().Bind(&hook.Handler[*core.RecordEvent]{
		Id:       "pbvexStorageQuotaUpdateExecute",
		Priority: 0,
		Func: func(e *core.RecordEvent) error {
			if err := s.nativeReserveUpload(e.Context, e.Record); err != nil {
				return err
			}
			return e.Next()
		},
	})

	// Settlement and credit after upstream commit/cleanup steps (-99).
	app.OnRecordAfterCreateSuccess().Bind(&hook.Handler[*core.RecordEvent]{
		Id:       "pbvexStorageQuotaAfterCreateSuccess",
		Priority: 0,
		Func: func(e *core.RecordEvent) error {
			s.nativeSettleUploads(e.Record)
			return e.Next()
		},
	})
	app.OnRecordAfterUpdateSuccess().Bind(&hook.Handler[*core.RecordEvent]{
		Id:       "pbvexStorageQuotaAfterUpdateSizes",
		Priority: -100,
		Func: func(e *core.RecordEvent) error {
			s.nativeStashDeleteSizes(e.App, e.Record)
			return e.Next()
		},
	})
	app.OnRecordAfterUpdateSuccess().Bind(&hook.Handler[*core.RecordEvent]{
		Id:       "pbvexStorageQuotaAfterUpdateSuccess",
		Priority: 0,
		Func: func(e *core.RecordEvent) error {
			s.nativeSettleUploads(e.Record)
			s.nativeCreditConfirmedDeletes(e.App, e.Record)
			return e.Next()
		},
	})

	// Failure handling: upstream cleanup interceptors run at -99; by the
	// time these handlers execute, deletion of failed uploads has been
	// attempted and its outcome is verifiable on the filesystem.
	for _, id := range []string{"pbvexStorageQuotaAfterCreateError", "pbvexStorageQuotaAfterUpdateError"} {
		app.OnRecordAfterCreateError().Bind(&hook.Handler[*core.RecordErrorEvent]{
			Id:       id,
			Priority: 0,
			Func: func(e *core.RecordErrorEvent) error {
				s.nativeHandleSaveError(e.App, e.Record)
				return e.Next()
			},
		})
		app.OnRecordAfterUpdateError().Bind(&hook.Handler[*core.RecordErrorEvent]{
			Id:       id,
			Priority: 0,
			Func: func(e *core.RecordErrorEvent) error {
				s.nativeHandleSaveError(e.App, e.Record)
				return e.Next()
			},
		})
	}

	// Record deletion: sizes are captured before the upstream file cleanup
	// interceptor (-99) deletes the objects, then credited after
	// confirming the removal.
	app.OnRecordAfterDeleteSuccess().Bind(&hook.Handler[*core.RecordEvent]{
		Id:       "pbvexStorageQuotaAfterDeleteSizes",
		Priority: -100,
		Func: func(e *core.RecordEvent) error {
			s.nativeStashRecordDeleteSizes(e.App, e.Record)
			return e.Next()
		},
	})
	app.OnRecordAfterDeleteSuccess().Bind(&hook.Handler[*core.RecordEvent]{
		Id:       "pbvexStorageQuotaAfterDeleteSuccess",
		Priority: 0,
		Func: func(e *core.RecordEvent) error {
			s.nativeCreditRecordDelete(e.App, e.Record)
			return e.Next()
		},
	})

	// Native on-demand thumbnail gate (files download route).
	app.OnServe().Bind(&hook.Handler[*core.ServeEvent]{
		Id: "pbvexStorageQuotaFileThumbGate",
		Func: func(se *core.ServeEvent) error {
			se.Router.BindFunc(func(e *core.RequestEvent) error {
				return s.nativeThumbGate(e)
			})
			return se.Next()
		},
	})

	return nil
}

// nativeFileFields returns the file fields of the record's collection.
func nativeFileFields(record *core.Record) []*core.FileField {
	var fields []*core.FileField
	for _, field := range record.Collection().Fields {
		if f, ok := field.(*core.FileField); ok {
			fields = append(fields, f)
		}
	}
	return fields
}

// nativeUploadableFiles extracts the pending *filesystem.File uploads of a
// file field value, mirroring the upstream extraction at the point where
// the interceptor reads raw values before the write.
func nativeUploadableFiles(value any) []*filesystem.File {
	var out []*filesystem.File
	appendFile := func(v any) {
		if f, ok := v.(*filesystem.File); ok && f != nil {
			out = append(out, f)
		}
	}
	switch v := value.(type) {
	case *filesystem.File:
		appendFile(v)
	case []*filesystem.File:
		for _, f := range v {
			appendFile(f)
		}
	case []any:
		for _, item := range v {
			appendFile(item)
		}
	}
	return out
}

// nativePlainNames extracts the plain stored file names of a file field
// value (after uploads have been renamed to their stored names).
func nativePlainNames(value any) []string {
	var out []string
	appendName := func(v any) {
		switch n := v.(type) {
		case string:
			if n != "" {
				out = append(out, n)
			}
		case *filesystem.File:
			if n != nil && n.Name != "" {
				out = append(out, n.Name)
			}
		}
	}
	switch v := value.(type) {
	case string:
		appendName(v)
	case []string:
		for _, n := range v {
			appendName(n)
		}
	case []any:
		for _, item := range v {
			appendName(item)
		}
	}
	return out
}

// nativeReserveUpload reserves worst-case bytes for all pending native
// uploads of a record before the upstream interceptor writes them. A
// denial or unavailability aborts the save before any write (fail closed).
func (s *Service) nativeReserveUpload(ctx context.Context, record *core.Record) error {
	var uploads []nativeUpload
	var total int64
	for _, field := range nativeFileFields(record) {
		for _, f := range nativeUploadableFiles(record.GetRaw(field.Name)) {
			if f == nil || f.Size < 0 {
				continue
			}
			uploads = append(uploads, nativeUpload{Field: field.Name, Name: f.Name, Size: f.Size})
			total += f.Size
		}
	}
	if total == 0 {
		// No pending uploads (save without file changes): nothing to
		// reserve. Removal credits for updates are handled in the
		// after-success passes.
		return nil
	}
	res, err := s.quotaReserve(ctx, QuotaReservationRequest{
		OpID:    newQuotaOpID("native"),
		Purpose: QuotaPurposeUpload,
		Key:     record.BaseFilesPath() + "/",
		// The multipart sizes are exact and already known; the worst case
		// is their total.
		WorstCase: total,
	})
	if err != nil {
		if errors.Is(err, ErrQuotaDenied) {
			return fmt.Errorf("native upload denied by storage quota: %w", err)
		}
		return fmt.Errorf("native upload quota check failed: %w", err)
	}
	record.SetRaw(nativeQuotaUploadStashKey, uploads)
	record.SetRaw(nativeQuotaReservationStashKey, res)
	return nil
}

// nativeSettleUploads settles the stashed reservation to the exact sizes
// of the uploads that the committed record actually stores.
func (s *Service) nativeSettleUploads(record *core.Record) {
	res, _ := record.GetRaw(nativeQuotaReservationStashKey).(QuotaReservation)
	stashed, _ := record.GetRaw(nativeQuotaUploadStashKey).([]nativeUpload)
	record.SetRaw(nativeQuotaReservationStashKey, nil)
	record.SetRaw(nativeQuotaUploadStashKey, nil)
	if res == nil || len(stashed) == 0 {
		return
	}
	stored := map[string]bool{}
	for _, field := range nativeFileFields(record) {
		for _, name := range nativePlainNames(record.GetRaw(field.Name)) {
			stored[name] = true
		}
	}
	var actual int64
	for _, u := range stashed {
		if stored[u.Name] {
			actual += u.Size
		}
	}
	s.quotaSettle(res, actual)
}

// nativeOriginalFileNames returns the stored file names of a file field as
// of the record's original DB state. Records that were never loaded from
// the database (in-memory instances) have a blank original; their current
// values are used as the deletion baseline instead.
func nativeOriginalFileNames(record *core.Record, fieldName string) []string {
	original := record.Original().GetRaw(fieldName)
	names := nativePlainNames(original)
	if len(names) == 0 {
		names = nativePlainNames(record.GetRaw(fieldName))
	}
	return names
}

// nativeStashDeleteSizes captures the sizes of the files an update removes
// (including their thumb variants) before the upstream interceptor deletes
// them. Only objects proven to exist here are eligible for credit later.
func (s *Service) nativeStashDeleteSizes(app core.App, record *core.Record) {
	var removals []nativeUpload
	for _, field := range nativeFileFields(record) {
		oldNames := nativeOriginalFileNames(record, field.Name)
		newNames := nativePlainNames(record.GetRaw(field.Name))
		for _, name := range oldNames {
			if slices.Contains(newNames, name) {
				continue
			}
			removal, ok := s.nativeRemovalOf(app, record, name)
			if !ok {
				continue
			}
			removal.Field = field.Name
			removals = append(removals, removal)
		}
	}
	if len(removals) > 0 {
		record.SetRaw(nativeQuotaDeleteStashKey, removals)
	}
}

// nativeCreditConfirmedDeletes credits the stashed removals whose objects
// are now verified absent.
func (s *Service) nativeCreditConfirmedDeletes(app core.App, record *core.Record) {
	stashed, _ := record.GetRaw(nativeQuotaDeleteStashKey).([]nativeUpload)
	record.SetRaw(nativeQuotaDeleteStashKey, nil)
	if len(stashed) == 0 || !s.hasQuota() {
		return
	}
	var freed int64
	for _, u := range stashed {
		if s.nativeConfirmedRemovalBytes(app, record, u) > 0 {
			freed += u.Size + u.ThumbBytes
		}
	}
	if freed <= 0 {
		return
	}
	s.quotaCredit(QuotaCreditRequest{
		OpID:  newQuotaOpID("native-delete"),
		Key:   record.BaseFilesPath() + "/",
		Bytes: freed,
	})
}

// nativeStashRecordDeleteSizes captures the sizes of all files and thumbs
// of a record before the upstream delete interceptor removes them.
func (s *Service) nativeStashRecordDeleteSizes(app core.App, record *core.Record) {
	var removals []nativeUpload
	for _, field := range nativeFileFields(record) {
		for _, name := range nativeOriginalFileNames(record, field.Name) {
			removal, ok := s.nativeRemovalOf(app, record, name)
			if !ok {
				continue
			}
			removal.Field = field.Name
			removals = append(removals, removal)
		}
	}
	if len(removals) > 0 {
		record.SetRaw(nativeQuotaDeleteStashKey, removals)
	}
}

// nativeCreditRecordDelete credits the record's captured file and variant
// bytes at the deletion commit. Upstream deletes the whole record files
// prefix asynchronously after the delete transaction (core/base.go
// "__pbFilesManagerDelete__" runs routine.FireAndForget), so a confirmed
// absence check cannot be made synchronously here; a failed background
// deletion can therefore transiently over-credit until the provider
// reconciles the actual object store.
func (s *Service) nativeCreditRecordDelete(_ core.App, record *core.Record) {
	stashed, _ := record.GetRaw(nativeQuotaDeleteStashKey).([]nativeUpload)
	record.SetRaw(nativeQuotaDeleteStashKey, nil)
	if len(stashed) == 0 || !s.hasQuota() {
		return
	}
	var freed int64
	for _, u := range stashed {
		freed += u.Size + u.ThumbBytes
	}
	if freed <= 0 {
		return
	}
	s.quotaCredit(QuotaCreditRequest{
		OpID:  newQuotaOpID("native-record-delete"),
		Key:   record.BaseFilesPath() + "/",
		Bytes: freed,
	})
}

// nativeHandleSaveError releases a failed save's reservation only when
// every uploaded object is verified absent. Any object that upstream
// cleanup could not delete leaves the reservation unsettled for provider
// reconciliation; the bytes are never silently released on an uncertain
// outcome.
func (s *Service) nativeHandleSaveError(app core.App, record *core.Record) {
	res, _ := record.GetRaw(nativeQuotaReservationStashKey).(QuotaReservation)
	stashed, _ := record.GetRaw(nativeQuotaUploadStashKey).([]nativeUpload)
	record.SetRaw(nativeQuotaReservationStashKey, nil)
	record.SetRaw(nativeQuotaUploadStashKey, nil)
	if res == nil || len(stashed) == 0 {
		return
	}
	fs, err := app.NewFilesystem()
	if err != nil {
		s.app.Logger().Warn("native upload failure cleanup unverifiable; keeping quota reservation",
			"reservationId", res.ID(), "error", err)
		return
	}
	defer fs.Close()
	for _, u := range stashed {
		path := record.BaseFilesPath() + "/" + u.Name
		exists, err := fs.Exists(path)
		if err != nil || exists {
			s.app.Logger().Warn("native upload failure left objects behind; keeping quota reservation for reconciliation",
				"reservationId", res.ID(), "error", err)
			return
		}
	}
	s.quotaRelease(res)
}

// nativeRemovalOf captures the exact size of a record file and its thumb
// variants (proof of existence) before a removal.
func (s *Service) nativeRemovalOf(app core.App, record *core.Record, name string) (nativeUpload, bool) {
	fs, err := app.NewFilesystem()
	if err != nil {
		return nativeUpload{}, false
	}
	defer fs.Close()
	attrs, err := fs.Attributes(record.BaseFilesPath() + "/" + name)
	if err != nil || attrs == nil || attrs.Size < 0 {
		return nativeUpload{}, false
	}
	removal := nativeUpload{Name: name, Size: attrs.Size}
	if objects, err := fs.List(record.BaseFilesPath() + "/thumbs_" + name + "/"); err == nil {
		for _, obj := range objects {
			if obj != nil && !obj.IsDir {
				removal.ThumbBytes += obj.Size
			}
		}
	}
	return removal, true
}

// nativeConfirmedRemovalBytes verifies the removal after the fact and
// returns the confirmed freed bytes (zero when the main object or any
// captured variant prefix is still present, so only verified removals are
// credited).
func (s *Service) nativeConfirmedRemovalBytes(app core.App, record *core.Record, u nativeUpload) int64 {
	fs, err := app.NewFilesystem()
	if err != nil {
		return 0
	}
	defer fs.Close()
	exists, err := fs.Exists(record.BaseFilesPath() + "/" + u.Name)
	if err != nil || exists {
		return 0
	}
	if u.ThumbBytes > 0 {
		objects, err := fs.List(record.BaseFilesPath() + "/thumbs_" + u.Name + "/")
		if err != nil || len(objects) > 0 {
			return 0
		}
	}
	return u.Size + u.ThumbBytes
}

// nativeThumbGate reserves bytes before the native files download route
// generates a missing thumbnail. It replicates the upstream generation
// conditions exactly so requests that upstream would serve without writing
// (invalid selector, non-image original, existing variant) are never
// blocked or double-counted. Concurrent requests for the same missing
// variant share one reservation through the gate.
func (s *Service) nativeThumbGate(e *core.RequestEvent) error {
	if e.Request.Method != http.MethodGet && e.Request.Method != http.MethodHead {
		return e.Next()
	}
	if !strings.HasPrefix(e.Request.URL.Path, "/api/files/") {
		return e.Next()
	}
	thumb := e.Request.URL.Query().Get("thumb")
	if thumb == "" {
		return e.Next()
	}
	collectionIdOrName := e.Request.PathValue("collection")
	recordId := e.Request.PathValue("recordId")
	filename := e.Request.PathValue("filename")
	if collectionIdOrName == "" || recordId == "" || filename == "" || strings.ContainsAny(filename, "/\\") {
		return e.Next()
	}
	collection, err := e.App.FindCachedCollectionByNameOrId(collectionIdOrName)
	if err != nil {
		// Upstream resolves the collection and returns its own 404.
		return e.Next()
	}
	record, err := e.App.FindRecordById(collection, recordId)
	if err != nil {
		return e.Next()
	}
	fileField := record.FindFileFieldByFile(filename)
	if fileField == nil {
		return e.Next()
	}
	// Mirror the upstream selector validation: unlisted selectors are
	// served the original bytes and never generate a variant.
	if thumb != nativeDefaultThumbSizes && !slices.Contains(fileField.Thumbs, thumb) {
		return e.Next()
	}
	baseFilesPath := record.BaseFilesPath()
	if collection.IsView() {
		fileRecord, err := e.App.FindRecordByViewFile(collection.Id, fileField.Name, filename)
		if err != nil {
			return e.Next()
		}
		baseFilesPath = fileRecord.BaseFilesPath()
	}
	originalKey := baseFilesPath + "/" + filename
	thumbKey := baseFilesPath + "/thumbs_" + filename + "/" + thumb + "_" + filename

	fs, err := e.App.NewFilesystem()
	if err != nil {
		return e.Next() // upstream surfaces its own filesystem error
	}
	attrs, err := fs.Attributes(originalKey)
	if err != nil {
		fs.Close()
		return e.Next() // upstream 404s
	}
	if !nativeIsImageContentType(attrs.ContentType) {
		fs.Close()
		return e.Next() // upstream serves the original
	}
	if exists, err := fs.Exists(thumbKey); err != nil || exists {
		fs.Close()
		return e.Next() // nothing to generate
	}
	// Bound the reservation from the original dimensions.
	width, height, ok := 0, 0, false
	if reader, rerr := fs.GetReader(originalKey); rerr == nil {
		width, height, ok = imageDimensions(reader)
		reader.Close()
	}
	fs.Close()
	if !ok {
		// Without decodable dimensions the variant size cannot be bounded;
		// fail closed instead of writing unreserved bytes.
		return e.InternalServerError("Failed to bound thumbnail storage.", ErrQuotaUnavailable)
	}
	worstCase := worstCaseThumbBytes(thumb, width, height)
	if worstCase <= 0 {
		return e.Next() // upstream treats the selector as invalid
	}

	leader, waiter := s.nativeVariants.acquire(thumbKey)
	if !leader {
		// Another in-flight request owns the reservation and the write for
		// this variant. Followers wait for the owning request to finish so
		// no second unreserved generation can start; the wait is bounded
		// and denies closed on timeout.
		select {
		case <-waiter.done:
			if waiter.ok {
				return e.Next()
			}
		case <-time.After(nativeVariantWaitTimeout):
		}
		return e.InternalServerError("Thumbnail storage quota unavailable.", ErrQuotaUnavailable)
	}

	res, err := s.quotaReserve(e.Request.Context(), QuotaReservationRequest{
		OpID:      newQuotaOpID("native-variant"),
		Purpose:   QuotaPurposeVariant,
		StorageID: "",
		Key:       thumbKey,
		WorstCase: worstCase,
	})
	if err != nil {
		s.nativeVariants.finish(thumbKey, waiter, false)
		if errors.Is(err, ErrQuotaDenied) {
			return e.InternalServerError("Thumbnail storage quota exhausted.", err)
		}
		return e.InternalServerError("Thumbnail storage quota check failed.", err)
	}

	serveErr := e.Next()
	if serveErr != nil {
		// Release only when the variant is confirmed absent; a possibly
		// partial write keeps the reservation for reconciliation. Followers
		// deny closed rather than retrying the write unreserved.
		s.releaseReservationIfGone(e.App, thumbKey, res)
		s.nativeVariants.finish(thumbKey, waiter, false)
		return serveErr
	}
	// The variant now exists (generated by this request or a concurrent
	// generation it joined): settle the reservation to the stored size. An
	// unreadable size leaves the reservation unsettled.
	if actual := quotaSettledBytesFrom(e.App, thumbKey); actual >= 0 {
		s.quotaSettle(res, actual)
	} else {
		s.quotaKeepForUncertainWrite(res, thumbKey)
	}
	s.nativeVariants.finish(thumbKey, waiter, true)
	return nil
}

// nativeIsImageContentType mirrors the upstream image content-type list of
// the pinned apis/file.go. Keep in sync when bumping PocketBase.
func nativeIsImageContentType(contentType string) bool {
	switch contentType {
	case "image/png", "image/jpg", "image/jpeg", "image/gif", "image/webp":
		return true
	}
	return false
}

// nativeVariantGate shares one thumbnail reservation between concurrent
// requests for the same missing variant. Followers wait until the owning
// request has settled, so a failed generation can never be retried by
// another request without its own reservation. Entries are removed when
// the owning request completes, keeping the map bounded by in-flight
// generation requests.
type nativeVariantGate struct {
	mu     sync.Mutex
	active map[string]*nativeVariantWaiter
}

type nativeVariantWaiter struct {
	done chan struct{}
	ok   bool
}

// nativeVariantWaitTimeout bounds how long a follower request waits for
// the owning generation to settle before denying closed.
const nativeVariantWaitTimeout = 30 * time.Second

func newNativeVariantGate() *nativeVariantGate {
	return &nativeVariantGate{active: map[string]*nativeVariantWaiter{}}
}

// acquire registers the caller as leader for the variant or returns the
// existing waiter to wait on.
func (g *nativeVariantGate) acquire(key string) (bool, *nativeVariantWaiter) {
	g.mu.Lock()
	defer g.mu.Unlock()
	if w, ok := g.active[key]; ok {
		return false, w
	}
	w := &nativeVariantWaiter{done: make(chan struct{})}
	g.active[key] = w
	return true, w
}

// finish unblocks followers with the outcome and removes the entry.
func (g *nativeVariantGate) finish(key string, w *nativeVariantWaiter, ok bool) {
	g.mu.Lock()
	if cur := g.active[key]; cur == w {
		delete(g.active, key)
	}
	w.ok = ok
	close(w.done)
	g.mu.Unlock()
}
