package deploy

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestComponentMountJSONPreservesArgsPresence(t *testing.T) {
	cases := []struct {
		name    string
		mount   ComponentMount
		wantKey bool
	}{
		{"absent", ComponentMount{Name: "m", ComponentID: "c"}, false},
		{"explicit null", ComponentMount{Name: "m", ComponentID: "c", ArgsPresent: true}, true},
		{"value", ComponentMount{Name: "m", ComponentID: "c", Args: "x"}, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			data, err := json.Marshal(tc.mount)
			if err != nil {
				t.Fatal(err)
			}
			var raw map[string]any
			if err := json.Unmarshal(data, &raw); err != nil {
				t.Fatal(err)
			}
			_, hasArgs := raw["args"]
			if hasArgs != tc.wantKey {
				t.Fatalf("args presence = %v, want %v: %s", hasArgs, tc.wantKey, data)
			}
			if _, leaked := raw["argsPresent"]; leaked {
				t.Fatalf("internal argsPresent leaked: %s", data)
			}
			var roundTrip ComponentMount
			if err := json.Unmarshal(data, &roundTrip); err != nil {
				t.Fatal(err)
			}
			if roundTrip.ArgsPresent != tc.wantKey {
				t.Fatalf("round-trip ArgsPresent = %v, want %v", roundTrip.ArgsPresent, tc.wantKey)
			}
		})
	}
}

func TestOptionalDescriptorIncludesAllOptionalObjects(t *testing.T) {
	allOptional := map[string]any{"type": "object", "shape": map[string]any{
		"a": map[string]any{"type": "optional", "validator": map[string]any{"type": "string"}},
		"b": map[string]any{"type": "defaulted", "validator": map[string]any{"type": "number"}, "defaultValue": float64(1)},
	}}
	if !isOptionalDescriptor(allOptional) {
		t.Fatal("all-optional object must accept omitted mount args")
	}
	required := map[string]any{"type": "object", "shape": map[string]any{
		"a": map[string]any{"type": "string"},
	}}
	if isOptionalDescriptor(required) {
		t.Fatal("object with a required field must require mount args")
	}

	definition := func(args any) map[string]any {
		return map[string]any{
			"componentId": "component",
			"modulePaths": []any{"m.ts"},
			"moduleHashes": map[string]any{
				"m.ts": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
			"args": args,
		}
	}
	graph := func(def map[string]any, mount map[string]any) map[string]any {
		return map[string]any{"definitions": []any{def}, "mounts": []any{mount}}
	}
	mount := map[string]any{"name": "component", "componentId": "component"}
	if _, err := ValidateComponents(graph(definition(allOptional), mount)); err != nil {
		t.Fatalf("all-optional object mount omission rejected: %v", err)
	}
	if _, err := ValidateComponents(graph(definition(required), mount)); err == nil {
		t.Fatal("required object mount omission must be rejected")
	}
	if _, err := ValidateComponents(graph(map[string]any{
		"componentId": "component",
		"modulePaths": []any{"m.ts"},
		"moduleHashes": map[string]any{
			"m.ts": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
		},
	}, map[string]any{"name": "component", "componentId": "component", "args": nil})); err == nil {
		t.Fatal("no-args component must reject explicit args")
	}
}

func TestComponentMountCanonicalPathBoundary(t *testing.T) {
	definition := map[string]any{
		"componentId":  "component",
		"modulePaths":  []any{"m.ts"},
		"moduleHashes": map[string]any{"m.ts": strings.Repeat("0", 64)},
	}
	segment := "a" + strings.Repeat("x", MaxIdentifierLength-1)
	build := func(depth int) map[string]any {
		var child map[string]any
		for i := depth - 1; i >= 0; i-- {
			mount := map[string]any{"name": segment, "componentId": "component"}
			if child != nil {
				mount["children"] = []any{child}
			}
			child = mount
		}
		return map[string]any{"definitions": []any{definition}, "mounts": []any{child}}
	}
	graph, err := ValidateComponents(build(32))
	if err != nil {
		t.Fatalf("maximum mount path rejected: %v", err)
	}
	namespaces, err := ComponentNamespaces(graph)
	if err != nil {
		t.Fatal(err)
	}
	wantLen := 32*MaxIdentifierLength + 31
	for path := range namespaces {
		if strings.Count(path, "/") == 31 && len(path) != wantLen {
			t.Fatalf("deepest path length = %d, want %d", len(path), wantLen)
		}
	}
	if _, err := ValidateComponents(build(33)); err == nil {
		t.Fatal("mount depth 33 accepted")
	}
}

// testBundleSha is a fixed SHA-256 hex used as the bundleSha in component
// identity tests. The actual value does not matter — what matters is that the
// same bundleSha is used to compute and authenticate the componentId.
const testBundleSha = "0000000000000000000000000000000000000000000000000000000000000000"

// validComponentDef is a content-addressed component definition whose
// componentId was generated by the TS bundler (buildComponentGraph) and is
// authenticated by authenticateComponentID. It includes bundleSha so the
// componentId binds to the executable bundle.
func validComponentDef() ComponentDefinition {
	def := ComponentDefinition{
		ComponentID: "", // computed below
		ModulePaths: []string{"messages.ts"},
		ModuleHashes: map[string]string{
			"messages.ts": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
		},
		Dependencies: []string{},
		Schema: map[string]any{
			"tables": []any{
				map[string]any{"tableName": "messages", "fields": map[string]any{}},
			},
		},
	}
	def.ComponentID = ComputeComponentID(def, testBundleSha)
	return def
}

func TestAuthenticateComponentIDAcceptsBundlerHash(t *testing.T) {
	if err := authenticateComponentID(validComponentDef(), testBundleSha); err != nil {
		t.Fatalf("expected valid componentId to authenticate: %v", err)
	}
}

func TestAuthenticateComponentIDRejectsTamperedHash(t *testing.T) {
	def := validComponentDef()
	last := def.ComponentID[len(def.ComponentID)-1]
	flipped := byte('a')
	if last == 'a' {
		flipped = 'b'
	}
	def.ComponentID = def.ComponentID[:len(def.ComponentID)-1] + string(flipped)
	if err := authenticateComponentID(def, testBundleSha); err == nil {
		t.Fatal("expected tampered componentId to be rejected")
	}
}

func TestAuthenticateComponentIDRejectsNonContentAddressed(t *testing.T) {
	def := validComponentDef()
	def.ComponentID = "myCustomCounter"
	if err := authenticateComponentID(def, testBundleSha); err == nil {
		t.Fatal("expected non content-addressed id to be rejected")
	}
}

func TestAuthenticateComponentIDRejectsBundleShaMismatch(t *testing.T) {
	def := validComponentDef()
	// A different bundleSha produces a different componentId, so authentication
	// with the wrong bundleSha must fail.
	wrongSha := "1111111111111111111111111111111111111111111111111111111111111111"
	if err := authenticateComponentID(def, wrongSha); err == nil {
		t.Fatal("expected bundleSha mismatch to be rejected")
	}
}

func TestComponentHashInputMatchesTSBundler(t *testing.T) {
	// Cross-language parity: the canonical hash of the reconstructed input must
	// equal the componentId computed with the same bundleSha. This proves the Go
	// hash computation is byte-identical to the TS bundler.
	def := validComponentDef()
	hash, err := CanonicalHash(componentHashInput(def, testBundleSha))
	if err != nil {
		t.Fatalf("hash: %v", err)
	}
	want := def.ComponentID
	got := "def_" + hash
	if got != want {
		t.Fatalf("hash mismatch: got %s want %s", got, want)
	}
}

func TestValidateComponentsRequiresDefinitionAndMountArrays(t *testing.T) {
	cases := []struct {
		name  string
		value any
	}{
		{"missing definitions", map[string]any{"mounts": []any{}}},
		{"missing mounts", map[string]any{"definitions": []any{}}},
		{"definitions not array", map[string]any{"definitions": "x", "mounts": []any{}}},
		{"unknown field", map[string]any{"definitions": []any{}, "mounts": []any{}, "extra": 1}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := ValidateComponents(tc.value); err == nil {
				t.Fatal("expected validation error")
			}
		})
	}
}

func TestValidateComponentsRejectsDuplicateModulePaths(t *testing.T) {
	raw := map[string]any{
		"definitions": []any{
			map[string]any{
				"componentId": "dup",
				"modulePaths": []any{"messages.ts", "messages.ts"},
				"moduleHashes": map[string]any{
					"messages.ts": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
				},
			},
		},
		"mounts": []any{},
	}
	_, err := ValidateComponents(raw)
	if err == nil || !strings.Contains(err.Error(), "duplicate") {
		t.Fatalf("expected duplicate modulePath error, got %v", err)
	}
}

func TestValidateComponentsRejectsBadEnvBinding(t *testing.T) {
	raw := map[string]any{
		"definitions": []any{
			map[string]any{
				"componentId": "envc",
				"modulePaths": []any{"messages.ts"},
				"moduleHashes": map[string]any{
					"messages.ts": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
				},
				"env": map[string]any{
					"KEY": map[string]any{"type": "envVar"},
				},
			},
		},
		"mounts": []any{},
	}
	if _, err := ValidateComponents(raw); err == nil {
		t.Fatal("expected envVar without name to fail")
	}
}

func TestValidateComponentFunctionBinding(t *testing.T) {
	def := ComponentDefinition{ComponentID: "c", ModulePaths: []string{"messages.ts"}}
	graph := &ComponentGraph{
		Definitions: []ComponentDefinition{def},
		Mounts:      []ComponentMount{{Name: "counter", ComponentID: "c"}},
	}

	valid := []FunctionDescriptor{
		{Name: "fn", ModulePath: "pbvex/components/counter/messages.ts"},
		{Name: "root", ModulePath: "pbvex/root.ts"},
	}
	if err := validateComponentFunctionBinding(valid, graph); err != nil {
		t.Fatalf("expected valid binding: %v", err)
	}

	orphan := []FunctionDescriptor{
		{Name: "fn", ModulePath: "pbvex/components/counter/widgets.ts"},
	}
	if err := validateComponentFunctionBinding(orphan, graph); err == nil {
		t.Fatal("expected orphan function to fail binding")
	}

	nomatch := []FunctionDescriptor{
		{Name: "fn", ModulePath: "pbvex/components/nowhere/messages.ts"},
	}
	if err := validateComponentFunctionBinding(nomatch, graph); err == nil {
		t.Fatal("expected unmatched mount prefix to fail binding")
	}
}

func TestValidateComponentFunctionBindingNestedMounts(t *testing.T) {
	def := ComponentDefinition{ComponentID: "c", ModulePaths: []string{"messages.ts"}}
	graph := &ComponentGraph{
		Definitions: []ComponentDefinition{def},
		Mounts: []ComponentMount{{
			Name:        "parent",
			ComponentID: "c",
			Children: []ComponentMount{{
				Name:        "child",
				ComponentID: "c",
			}},
		}},
	}
	// Longest-prefix match: parent has prefix pbvex/components/parent/, child
	// has pbvex/components/parent/child/. The longest match wins.
	cases := []struct {
		modulePath string
		ok         bool
	}{
		{"pbvex/components/parent/messages.ts", true},
		{"pbvex/components/parent/child/messages.ts", true},
		{"pbvex/components/parent/other.ts", false},
	}
	for _, tc := range cases {
		err := validateComponentFunctionBinding([]FunctionDescriptor{{Name: "fn", ModulePath: tc.modulePath}}, graph)
		if tc.ok && err != nil {
			t.Errorf("%s: expected ok, got %v", tc.modulePath, err)
		}
		if !tc.ok && err == nil {
			t.Errorf("%s: expected error", tc.modulePath)
		}
	}
}

func TestValidateComponentsRejectsParentModuleInsideDescendantMount(t *testing.T) {
	hash := "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
	raw := map[string]any{
		"definitions": []any{
			map[string]any{
				"componentId":  "parent",
				"modulePaths":  []any{"child/store.ts"},
				"moduleHashes": map[string]any{"child/store.ts": hash},
			},
			map[string]any{
				"componentId":  "child",
				"modulePaths":  []any{"store.ts"},
				"moduleHashes": map[string]any{"store.ts": hash},
			},
		},
		"mounts": []any{
			map[string]any{
				"name":        "outer",
				"componentId": "parent",
				"children": []any{
					map[string]any{"name": "child", "componentId": "child"},
				},
			},
		},
	}
	if _, err := ValidateComponents(raw); err == nil || !strings.Contains(err.Error(), "collides with descendant mount") {
		t.Fatalf("expected nested module ownership collision, got %v", err)
	}
}

// TestEmptyEnvIncludedInHashInput verifies that an explicit empty env map
// (present but empty) is included in the component hash input, matching the
// TS bundler/protocol which includes env:{} when env is defined. A nil env
// (absent) is excluded.
func TestEmptyEnvIncludedInHashInput(t *testing.T) {
	base := ComponentDefinition{
		ModulePaths:  []string{"m.ts"},
		ModuleHashes: map[string]string{"m.ts": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"},
		Dependencies: []string{},
	}
	bundleSha := "abc123"

	withEnv := base
	withEnv.Env = map[string]EnvArgDescriptor{} // present but empty

	inputWith := componentHashInput(withEnv, bundleSha)
	_, hasEnv := inputWith["env"]
	if !hasEnv {
		t.Fatal("expected env key in hash input when Env is non-nil empty map")
	}
	envMap, ok := inputWith["env"].(map[string]any)
	if !ok || len(envMap) != 0 {
		t.Fatalf("expected empty env map, got %#v", inputWith["env"])
	}

	inputWithout := componentHashInput(base, bundleSha)
	_, hasEnv = inputWithout["env"]
	if hasEnv {
		t.Fatal("expected no env key in hash input when Env is nil")
	}

	// Different hashes: including env:{} changes the componentId.
	idWith := ComputeComponentID(withEnv, bundleSha)
	idWithout := ComputeComponentID(base, bundleSha)
	if idWith == idWithout {
		t.Fatal("expected different componentIds for empty-env-present vs env-absent")
	}
}

func TestPhysicalIdentityPreflightRejectsRootComponentAlias(t *testing.T) {
	namespace, err := ComponentNamespaceID("mounted")
	if err != nil {
		t.Fatal(err)
	}
	physical, err := ComponentCollectionName(namespace, "items")
	if err != nil {
		t.Fatal(err)
	}
	componentSchema := map[string]any{"tables": []any{map[string]any{
		"tableName": "items", "fields": map[string]any{},
		"indexes": []any{map[string]any{"name": "by_id", "fields": []any{"_id"}}},
	}}}
	manifest := DeploymentManifest{
		Schema: map[string]any{"tables": []any{map[string]any{"tableName": physical, "fields": map[string]any{}}}},
		Components: &ComponentGraph{
			Definitions: []ComponentDefinition{{ComponentID: "component", Schema: componentSchema}},
			Mounts:      []ComponentMount{{Name: "mounted", ComponentID: "component"}},
		},
	}
	namespaces, err := ComponentNamespaces(manifest.Components)
	if err != nil {
		t.Fatal(err)
	}
	if err := preflightPhysicalIdentities(manifest, namespaces); err == nil {
		t.Fatal("root logical table aliased a derived component collection")
	}
}
