#!/usr/bin/env node
// @ts-check
/**
 * Regenerates docs/api-reference/ from the TypeScript and Go source of truth.
 * Run with `pnpm docs:api` (which also builds packages when needed).
 */
import { execFileSync } from 'node:child_process';
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const root = resolve(__dirname, '..');
const docsDir = join(root, 'docs');
const apiRefDir = join(docsDir, 'api-reference');
const tsApiDir = join(apiRefDir, 'ts');
const goApiDir = join(apiRefDir, 'go');

const tsPackages = [
  {
    name: 'protocol',
    packageName: '@pbvex/protocol',
    entryPoints: ['packages/protocol/src/index.ts'],
    tsconfig: 'packages/protocol/tsconfig.json',
  },
  {
    name: 'pbvex',
    packageName: 'pbvex',
    entryPoints: [
      'packages/pbvex/src/runtime/index.ts',
      'packages/pbvex/src/runtime/server.ts',
      'packages/pbvex/src/runtime/values.ts',
      'packages/pbvex/src/runtime/component.ts',
    ],
    tsconfig: 'packages/pbvex/tsconfig.json',
  },
  {
    name: 'sdk-core',
    packageName: '@pbvex/sdk-core',
    entryPoints: ['packages/sdk-core/src/index.ts'],
    tsconfig: 'packages/sdk-core/tsconfig.json',
  },
  {
    name: 'sdk-react',
    packageName: '@pbvex/sdk-react',
    entryPoints: ['packages/sdk-react/src/index.ts'],
    tsconfig: 'packages/sdk-react/tsconfig.json',
  },
  {
    name: 'sdk-svelte',
    packageName: '@pbvex/sdk-svelte',
    entryPoints: ['packages/sdk-svelte/src/index.ts'],
    tsconfig: 'packages/sdk-svelte/tsconfig.json',
  },
];

const goModuleUrl = 'https://github.com/nathabonfim59/pbvex';
const goDefaultBranch = 'master';
const goRepositoryPath = '/';
const gomarkdocVersion = 'v1.1.0';

function toPosix(p) {
  return p.replace(/\\/g, '/');
}

function run(cmd, args, options = {}) {
  return execFileSync(cmd, args, { stdio: 'inherit', cwd: root, ...options });
}

function ensureBuild() {
  const needed = tsPackages.map((pkg) => {
    if (pkg.name === 'pbvex') {
      return 'packages/pbvex/dist/runtime/index.d.ts';
    }
    return `packages/${pkg.name}/dist/index.d.ts`;
  });
  if (needed.some((p) => !existsSync(join(root, p)))) {
    console.log('Building packages before generating API docs...');
    run('pnpm', ['run', 'build']);
  }
}

function generatePackageDocs(pkg) {
  const outDir = join(tsApiDir, pkg.name);
  const options = {
    plugin: ['typedoc-plugin-markdown', 'typedoc-vitepress-theme'],
    entryPoints: pkg.entryPoints.map((ep) => resolve(root, ep)),
    tsconfig: resolve(root, pkg.tsconfig),
    out: outDir,
    cleanOutputDir: true,
    disableSources: true,
    excludeExternals: true,
    excludePrivate: true,
    excludeProtected: true,
    excludeInternal: true,
    sort: ['kind', 'alphabetical'],
    readme: 'none',
    docsRoot: docsDir,
  };
  const tmpDir = mkdtempSync(join(tmpdir(), 'pbvex-typedoc-'));
  const optionsFile = join(tmpDir, 'typedoc.json');
  writeFileSync(optionsFile, JSON.stringify(options, null, 2));
  try {
    console.log(`Generating TypeScript API docs for ${pkg.packageName}...`);
    run('pnpm', ['exec', 'typedoc', '--options', optionsFile]);
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
  const packageIndex = join(outDir, 'index.md');
  if (existsSync(packageIndex)) {
    const marker = `<!-- Generated by pnpm docs:api via TypeDoc. Source of truth: ${pkg.packageName} source. Do not edit manually. -->\n\n`;
    writeFileSync(packageIndex, marker + readFileSync(packageIndex, 'utf-8'));
  }
}

function generateGoDocs() {
  const outputPattern = join(goApiDir, '{{.Dir}}', 'index.md');
  console.log('Generating Go API docs...');
  run('go', [
    'run',
    `github.com/princjef/gomarkdoc/cmd/gomarkdoc@${gomarkdocVersion}`,
    '--repository.url',
    goModuleUrl,
    '--repository.default-branch',
    goDefaultBranch,
    '--repository.path',
    goRepositoryPath,
    '--output',
    outputPattern,
    './backend/...',
  ]);
}

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf-8'));
}

function packageDescription(pkgName) {
  try {
    const pkg = readJson(join(root, 'packages', pkgName, 'package.json'));
    return pkg.description || '';
  } catch {
    return '';
  }
}

function findGoPackageIndexes(dir) {
  const result = [];
  if (!existsSync(dir)) return result;
  function walk(current) {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const entryPath = join(current, entry.name);
      if (entry.isDirectory()) {
        walk(entryPath);
      } else if (entry.isFile() && entry.name === 'index.md') {
        const relDir = toPosix(relative(dir, current));
        result.push({
          path: relDir,
          filePath: entryPath,
          link: '/api-reference/go/' + relDir + '/',
        });
      }
    }
  }
  walk(dir);
  return result.sort((a, b) => a.path.localeCompare(b.path));
}

function firstHeading(filePath) {
  try {
    const content = readFileSync(filePath, 'utf-8');
    const match = content.match(/^#\s+(.+)$/m);
    return match ? match[1].trim() : '';
  } catch {
    return '';
  }
}

function writeGeneratedMarkdown(filePath, title, body) {
  const marker = `<!-- Generated by pnpm docs:api. Source of truth: the backend and TypeScript source. Do not edit manually. -->`;
  const content = `${marker}\n\n# ${title}\n\n${body}`;
  writeFileSync(filePath, content);
}

function generateTopLevelIndexes() {
  const tsPackagesList = tsPackages
    .map((pkg) => {
      const desc = packageDescription(pkg.name);
      return `- [${pkg.packageName}](/api-reference/ts/${pkg.name}/) — ${desc}`;
    })
    .join('\n');

  writeGeneratedMarkdown(
    join(tsApiDir, 'index.md'),
    'TypeScript API Reference',
    `This section documents the public exports of the five PBVex TypeScript packages. Each page is generated from the package source by TypeDoc.\n\n${tsPackagesList}`,
  );

  const goPackages = findGoPackageIndexes(goApiDir);
  const executable = goPackages.filter((p) => p.path === 'backend/cmd/pbvex');
  const internal = goPackages.filter((p) => p.path.includes('/internal/'));
  const other = goPackages.filter((p) => !executable.includes(p) && !internal.includes(p));

  const goList = (list) =>
    list
      .map((p) => {
        const heading = firstHeading(p.filePath) || p.path;
        return `- [${heading}](${p.link}) \`${p.path}\``;
      })
      .join('\n') || '_No packages generated._';

  const goBody = [
    'This section documents the Go backend surface. The executable is the `cmd/pbvex` package. Other packages are primarily internal implementation details; their import paths contain `/internal/`.',
    '## Executable',
    goList(executable),
    '## Internal packages',
    goList(internal),
    other.length ? '## Other packages\n\n' + goList(other) : '',
  ]
    .filter((s) => s.trim() !== '## Other packages')
    .filter(Boolean)
    .join('\n\n');

  writeGeneratedMarkdown(
    join(goApiDir, 'index.md'),
    'Go API Reference',
    goBody,
  );

  writeGeneratedMarkdown(
    join(apiRefDir, 'index.md'),
    'API Reference',
    `This API reference is generated from source.\n\n- [TypeScript API reference](/api-reference/ts/) — generated from the five publishable packages.\n- [Go API reference](/api-reference/go/) — generated from the backend source by gomarkdoc.\n\nRun \`pnpm docs:api\` to regenerate these pages.`,
  );
}

function mkdirRecursive(dir) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function main() {
  ensureBuild();
  rmSync(apiRefDir, { recursive: true, force: true });
  mkdirRecursive(tsApiDir);
  mkdirRecursive(goApiDir);

  for (const pkg of tsPackages) {
    generatePackageDocs(pkg);
  }

  generateGoDocs();
  generateTopLevelIndexes();

  console.log('API docs generated at', relative(root, apiRefDir));
}

main();
